#last fetch: 2024-09-04 09:27:07.959950
UseConstraint = {'CC0-1.0': {'exactMatch': ['http://spdx.org/licenses/CC0-1.0', 'https://creativecommons.org/publicdomain/zero/1.0/'], 'altLabel': ['Creative Commons Zero v1.0 Universal', 'CC0 1.0']}, 'CC-BY-4.0': {'exactMatch': ['http://spdx.org/licenses/CC-BY-4.0', 'https://creativecommons.org/licenses/by/4.0/'], 'altLabel': ['Creative Commons Attribution 4.0 International', 'Attribution', 'CC BY 4.0']}, 'CC-BY-SA-4.0': {'exactMatch': ['http://spdx.org/licenses/CC-BY-SA-4.0', 'https://creativecommons.org/licenses/by-sa/4.0/'], 'altLabel': ['Creative Commons Attribution Share Alike 4.0 International', 'Attribution-ShareAlike', 'CC BY-SA 4.0']}, 'CC-BY-NC-4.0': {'exactMatch': ['http://spdx.org/licenses/CC-BY-NC-4.0', 'https://creativecommons.org/licenses/by-nc/4.0/'], 'altLabel': ['Creative Commons Attribution Non Commercial 4.0 International', 'Attribution-NonCommercial', 'CC BY-NC 4.0']}, 'CC-BY-NC-SA-4.0': {'exactMatch': ['http://spdx.org/licenses/CC-BY-NC-SA-4.0', 'https://creativecommons.org/licenses/by-nc-sa/4.0/'], 'altLabel': ['Creative Commons Attribution Non Commercial Share Alike 4.0 International', 'Attribution-NonCommercial-ShareAlike', 'CC BY-NC-SA 4.0']}, 'CC-BY-ND-4.0': {'exactMatch': ['http://spdx.org/licenses/CC-BY-ND-4.0', 'https://creativecommons.org/licenses/by-nd/4.0/'], 'altLabel': ['Creative Commons Attribution No Derivatives 4.0 International', 'Attribution-NoDerivs', 'CC BY-ND 4.0']}, 'CC-BY-NC-ND-4.0': {'exactMatch': ['https://creativecommons.org/licenses/by-nc-nd/4.0/', 'http://spdx.org/licenses/CC-BY-NC-ND-4.0'], 'altLabel': ['Creative Commons Attribution Non Commercial No Derivatives 4.0 International', 'Attribution-NonCommercial-NoDerivs', 'CC BY-NC-ND 4.0']}, 'CC-BY-3.0': {'exactMatch': ['http://spdx.org/licenses/CC-BY-3.0', 'https://creativecommons.org/licenses/by/3.0/'], 'altLabel': ['Creative Commons Attribution 3.0 Unported', 'CC BY 3.0']}}
AccessConstraint = ['Open', 'Registered users only (automated approval)', 'Registered users only (manual approval required)', 'Restricted to a community', 'Restricted access to metadata']
ActivityType = ['Aircraft', 'Space Borne Instrument', 'Numerical Simulation', 'Climate Indicator', 'In Situ Land-based station', 'In Situ Ship-based station', 'In Situ Ocean fixed station', 'In Situ Ocean moving station', 'In Situ Ice-based station', 'Interview/Questionnaire', 'Maps/Charts/Photographs', 'Not available']
OperationalStatus = ['Operational', 'Pre-Operational', 'Experimental', 'Scientific', 'Not available']
AccessConstraint = ['Open', 'Registered users only (automated approval)', 'Registered users only (manual approval required)', 'Restricted to a community', 'Restricted access to metadata']
CollectionKeywords = ['CC', 'NMAP', 'ADC', 'GCW', 'NMDC', 'SIOS', 'NSDN', 'DOKI', 'DAM', 'ACCESS', 'NBS', 'APPL', 'YOPP', 'METNCS', 'SESS2018', 'SESS2019', 'SESS2020', 'SESS2022', 'SIOSCD', 'SIOSAP', 'SIOSIN', 'CVL', 'AeN', 'TONE', 'NySMAC', 'KSS', 'GEONOR']
ISOTopicCategory = ['inlandWaters', 'intelligenceMilitary', 'climatologyMeteorologyAtmosphere', 'utilitiesCommunications', 'farming', 'imageryBaseMapsEarthCover', 'structure', 'health', 'elevation', 'society', 'environment', 'extraTerrestrial', 'biota', 'disaster', 'transportation', 'geoscientificInformation', 'oceans', 'economy', 'planningCadastre', 'location', 'boundaries', 'Not available']
DatasetProductionStatus = ['Planned', 'In Work', 'Complete', 'Obsolete', 'Not available']
RelatedInformationTypes = ['Project home page', 'Users guide', 'Dataset landing page', 'Scientific publication', 'Data paper', 'Data management plan', 'Software', 'Other documentation', 'Observation facility', 'Extended metadata']
ISOTopicCategory = ['inlandWaters', 'intelligenceMilitary', 'climatologyMeteorologyAtmosphere', 'utilitiesCommunications', 'farming', 'imageryBaseMapsEarthCover', 'structure', 'health', 'elevation', 'society', 'environment', 'extraTerrestrial', 'biota', 'disaster', 'transportation', 'geoscientificInformation', 'oceans', 'economy', 'planningCadastre', 'location', 'boundaries', 'Not available']
KeywordsVocabulary = ['GCMDSK', 'GCMDLOC', 'GCMDPROV', 'CFSTDN', 'GEMET', 'NORTHEMES', 'None']
