#!/usr/bin/env python3
#
# Name:
# add_parent
#
# Purpose:
# Add a parent identifier to a child dataset. 
# 
# Author:
# Øystein Godøy, METNO/FOU, 2020-10-06, original version
#
import sys
import os
import argparse
import lxml.etree as ET
from datetime import datetime
import pytz

if __name__ == '__main__':
    # Parse command line arguments
    parser = argparse.ArgumentParser(
            description='Add parent record to MMD records. '+
            'For handling of multiple files run through find.')
    parser.add_argument('parentid', type=str, 
            help='UUID of parent record')
    parser.add_argument('infile', type=str, 
            help='File to update')
    try:
        args = parser.parse_args()
    except:
        parser.print_help()
        sys.exit()

    # Read input file
    try:
        myxml = ET.parse(args.infile)
    except:
        print("Couldn't parse input file", args.infile)
        sys.exit()

    myroot = myxml.getroot()

    # Add related_dataset
    mynode = ET.Element("{http://www.met.no/schema/mmd}related_dataset",
            relation_type='parent')
    mynode.text = args.parentid

    myroot.insert(-1, mynode)

    # Dump results to file
    myxml.write(args.infile, pretty_print=True)
