#!/usr/bin/env python3
import sys
import getopt

from mmd_utils.createMETUUID import create_MET_uuid

def usage():
  print ('Usage: '+sys.argv[0]+' -i <mdfile> [-w]')  
  print ('   -i: input file')
  print ('   -w: overwrite input file')
  sys.exit(2)

def main(argv):
    infile = None
    overwrite = False
    try:
        opts, args = getopt.getopt(argv,"hi:w",["ifile="])
    except getopt.GetoptError:
        print (str(err))
        usage()
    for opt, arg in opts:
        if opt == '-h':
            usage()
            sys.exit()
        elif opt in ("-i", "--ifile"):
            infile = arg
        elif opt in ("-w"):
            overwrite = True
        else:
            assert False, 'Unhandled option'

    if infile is None: 
        usage()

    create_MET_uuid(infile, overwrite)

if __name__ == "__main__":
    main(sys.argv[1:])
