#!/usr/bin/env python3
#
# Name:
# traverse_thredds
#
# Purpose:
# Traverse THREDDS catalogs and extract discovery metadata into MMD files
# for datasets having ACDD elements.
# 
# Author:
# Øystein Godøy, METNO/FOU, 2020-10-06, original version
#
import sys
import os
import argparse
from mdh_modules.mdh_utils import initialise_logger
from mdh_modules.traverse_thredds_utils import traverse_thredds

if __name__ == '__main__':
    # Parse command line arguments
    parser = argparse.ArgumentParser(
            description='Traverse THREDDS catalogues and extract '+
            'discovery metadata to MMD where ACDD elements are present')
    parser.add_argument('starturl', type=str, 
            help='URL to start traverse')
    parser.add_argument('dstdir', type=str, 
            help='Directory where to put MMD files')
    parser.add_argument('-d', '--depth', type=int, default=3, 
            help='Directory where to put MMD files')
    parser.add_argument("-l","--logfile",dest="logfile", help="Log file", required=True)
    
    try:
        args = parser.parse_args()
    except:
        parser.print_help()
        sys.exit()
    
    # Set up logging
    mylog = initialise_logger(args.logfile,'traverse_thredds')
    mylog.info('\n==========\nConfiguration of logging is finished.')

    try:
        traverse_thredds(args.starturl, args.dstdir, args.depth, mylog)
    except Exception as e:
        mylog.error('Something went wrong:', e)
        sys.exit()
    sys.exit()
